-- ============================================================================
-- FIX: IDENTITY COLUMNS (GENERATED ALWAYS -> BY DEFAULT)
-- ============================================================================
-- Supabase/PostgREST sometimes struggles with "GENERATED ALWAYS" if the client
-- sends any value (even null/undefined) for the ID. "BY DEFAULT" is safer.

BEGIN;

-- 1. Fix wh_graphs
ALTER TABLE public.wh_graphs ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_graphs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Fix wh_nodes
ALTER TABLE public.wh_nodes ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Fix wh_edges
ALTER TABLE public.wh_edges ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_edges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 4. Fix wh_requests
ALTER TABLE public.wh_requests ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 5. Fix wh_assignments
ALTER TABLE public.wh_assignments ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 6. Fix wh_tasks
ALTER TABLE public.wh_tasks ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 7. Fix wh_robots
ALTER TABLE public.wh_robots ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_robots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

COMMIT;

-- Reload Cache
NOTIFY pgrst, 'reload config';

SELECT '✅ Identity columns changed to GENERATED BY DEFAULT' as status;
