-- ============================================================================
-- FIX: DATABASE SEQUENCE & PERMISSIONS (THE ONE SCRIPT TO FIX THEM ALL)
-- ============================================================================
-- 1. Changes Identity Columns to GENERATED BY DEFAULT (allows manual overrides).
-- 2. RESETS Sequences to max(id) + 1 (Fixes "duplicate key" errors).
-- 3. Grants Permissions (Fixes "permission denied" errors).

BEGIN;

-- --- PART 1: RELAX IDENTITY CONSTRAINTS ---
ALTER TABLE public.wh_graphs ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_graphs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_nodes ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_edges ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_edges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_requests ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_assignments ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_tasks ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.wh_robots ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.wh_robots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- --- PART 2: RESET SEQUENCES (CRITICAL FOR "DUPLICATE KEY" ERRORS) ---
-- This ensures the next auto-generated ID is higher than any existing ID.

SELECT setval(pg_get_serial_sequence('public.wh_graphs', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_graphs;
SELECT setval(pg_get_serial_sequence('public.wh_nodes', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_nodes;
SELECT setval(pg_get_serial_sequence('public.wh_edges', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_edges;
SELECT setval(pg_get_serial_sequence('public.wh_requests', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_requests;
SELECT setval(pg_get_serial_sequence('public.wh_assignments', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_assignments;
SELECT setval(pg_get_serial_sequence('public.wh_tasks', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_tasks;
SELECT setval(pg_get_serial_sequence('public.wh_robots', 'id'), COALESCE(max(id), 0) + 1, false) FROM public.wh_robots;


-- --- PART 3: RE-GRANT PERMISSIONS ---
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;

-- Reload Cache
NOTIFY pgrst, 'reload config';

SELECT '✅ DATABASE FULLY REPAIRED: Identity types fixed, Sequences reset, Permissions granted.' as status;
